### ISSUE TITLE
Если в коллекции есть объект с пустой категорией, count_greater_than_category с не пустым аргументом выдаёт ошибку

### ISSUE THREAD

**Issue by Bibletoon** [Leatherlord/LabsProgramming#14]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "AstartesCategory.compareTo(java.lang.Enum)" because the return value of "SpaceMarine.getCategory()" is null
        at Commands.countGCategory(Commands.java:210)
        at CommandReader.read(CommandReader.java:189)
        at CommandReader.<init>(CommandReader.java:10)
        at Main.main(Main.java:24)

**Comment by Leatherlord** [comment]
f1321db053ebcb8b6b453379d8d93f728686c596
@Bibletoon
